export interface MeduimBlog {
  title: string;
  link: string;
  author: string;
  published: number;
  created: number;
  category: string[];
  content: string;
  enclosures: any[];
  content_encoded: string;
}

// Generated by https://quicktype.io

export interface Blog {
  title: string[];
  link: string[];
  category: string[];
  "dc:creator": string[];
  pubDate: string[];
  "atom:updated": string[];
  "content:encoded": string[];
}
